resolver 127.0.0.11 valid=30s;

server {
    listen 80;
    server_name blog.yeyeyiyi.online;

    location /api/ {
        proxy_pass http://backend:8000;
    }

    location /uploads/ {
        proxy_pass http://backend:8000;
    }

    location / {
        proxy_pass http://frontend:3000;
    }
}

server {
    listen 80;
    server_name admin.yeyeyiyi.online;

    location /api/ {
        proxy_pass http://backend:8000;
    }

    location /uploads/ {
        proxy_pass http://backend:8000;
    }

    location / {
        proxy_pass http://admin:80;
    }
}

server {
    listen 80;
    server_name api.yeyeyiyi.online;

    location / {
        proxy_pass http://backend:8000;
    }
}
